# Generated by Django 2.1.7 on 2019-02-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_grocery_completed'),
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='groceries',
            field=models.ManyToManyField(blank=True, null=True, to='groceries.Grocery'),
        ),
    ]
