# Generated by Django 2.1.7 on 2019-02-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
