# Generated by Django 2.1.7 on 2019-02-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_list_groceries'),
        ('list', '0003_auto_20190225_1358'),
    ]

    operations = [
    ]
