# Generated by Django 2.1.7 on 2019-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
