# Generated by Django 2.1.7 on 2019-03-21 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groceries', '0003_grocery_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='completedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complete', to=settings.AUTH_USER_MODEL),
        ),
    ]
